# Generated by Django 4.1.2 on 2022-10-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slider',
            field=models.BooleanField(default=False),
        ),
    ]
