# Generated by Django 4.1.2 on 2022-10-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Site Details', 'verbose_name_plural': 'Site Details'},
        ),
    ]
