# Generated by Django 4.1.2 on 2022-10-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_alter_about_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='address',
            field=models.TextField(default='NewsFeed, 1238 S . 123 St.Suite 25 Lagos, Nigeria', null=True),
        ),
    ]
