# Generated by Django 4.1.2 on 2022-10-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_alter_about_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='facebook',
            field=models.CharField(default='https://facebook.com', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='google',
            field=models.CharField(default='https://google.com', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='pinterest',
            field=models.CharField(default='https://pinterest.com', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='twitter',
            field=models.CharField(default='https://twitter.com', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='vimeo',
            field=models.CharField(default='https://vimeo.com', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='youtube',
            field=models.CharField(default='https://youtube.com', max_length=10000, null=True),
        ),
    ]
