# Generated by Django 4.1.2 on 2022-10-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_about_facebook_about_google_about_pinterest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='google',
        ),
        migrations.AddField(
            model_name='about',
            name='flickr',
            field=models.CharField(default='https://flickr.com', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='googleplus',
            field=models.CharField(default='https://accounts.google.com', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='mail',
            field=models.CharField(default='https://mail.google.com', max_length=10000, null=True),
        ),
    ]
